### PR TITLE
React to name changes in TagHelpers

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by dougbu** [comment]
@rynowak thx I was thinking of doing this too :smiley_cat:  LGTM but @avanderhoorn should have the final say since users might not be building this with the bleeding edge bits.

**Comment by avanderhoorn** [comment]
@rynowak Thanks! But what you mean by grunt is sad?

**Comment by rynowak** [comment]
It doesn't run on my box. I guess maybe I was the one who was sad.

**Pull request merged**
