### PR TITLE
Event

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Looks like I can't just pull this in yet. Any chance you can fix up when you get a chance?

**Comment by rynowak** [comment]
@avanderhoorn updated

**Comment by avanderhoorn** [comment]
Thanks!

**Comment by avanderhoorn** [comment]
@rynowak Looks like there was a bad merge when the PR got submitted - https://github.com/avanderhoorn/Glimpse.Prototype/blob/dev/src/Glimpse.Agent.Common/Broker/DefaultAgentBroker.cs#L33. The context is never being set, any thoughts?

**Pull request merged**
