### PR TITLE
Updated Target Framework to .net45 / netcoreapp1.1

### PR DESCRIPTION
**Pull request by dkald**
Removes redundant usings

### CODE REVIEW

**Comment by dkald** [comment]
Hi, really liking what i am seeing, planning on poking this into a project I am currently on. thought i would post the changes made. and hopefully get some feedback from the gurus. if any of this is out of line / place. let me know

~dkald

**Comment by Jetski5822** [comment]
I'm gunna try this for Orchard Core/Orchard 2 - ill let you know how it goes

**Comment by Jetski5822** [comment]
@dkald There are issues with the build stuff, is there a place I can do a PR to your branch?

**Comment by dkald** [comment]
hey jetski, no issues with doing it direct, feel free on taking over this bud, moving in a different direction, hope its turns out useful to you

**Pull request closed without merging**
