### PR TITLE
Adding devenv script to run necessary dnvm/dnu commands to address #60

### PR DESCRIPTION
**Pull request by mike-kaufman**
Adding a script called devenv.cmd to run the necessary dnvm/dnu commands that will update/refresh .net version manager & associated libraries.  Furthermore, this script can be a place where any further "dev environment configurations"  can happen.

Please let me know if there is feedback.

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Script looks good... what do we think about `devenv.cmd` vs `setup.cmd` or `setup-dev.cmd`?

**Comment by mike-kaufman** [comment]
Well, I called it "devenv.cmd", as in the future, it could be run to set up a "dev shell" - e.g., we could set the env up appropriately for the project (e.g., setting DNX_FEED and DNX_UNSTABLE_FEED), and we could define a set of aliases to make things convenient.  

That said, I wanted to raise this as a discussion point.  We can call it whatever you think makes sense. :)

**Comment by nikmd23** [comment]
I'm pulling this in.

If we find the name to be confusing, we can always change it later.

**Comment by avanderhoorn** [comment]
:+1:

**Pull request merged**
