### PR TITLE
Appending html to PostContent rather than set

### LINKED ISSUE #91: ScriptInjector overwriting all PostContent
When adding the scripts for Glimpse in [ScriptInjector](https://github.com/Glimpse/Glimpse.Prototype/blob/dev/src/Glimpse.Agent.AspNet.Mvc/Razor/ScriptInjector.cs#L24-L26) and using `PostContent.SetHtmlContent` any other tag helpers that append to PostContent for the body tag are getting overwritten.

Could this be changed to `output.PostContent.AppendHtml` to play nice wither others using the PostContent area?

### PR DESCRIPTION
**Pull request by damienpontifex**
Resolves #91 by appending html to post content rather than overwriting with setcontent

### CODE REVIEW

**Comment by avanderhoorn** [comment]
@damienpontifex great pickup! In your test, I'm assuming that things work correct in both cases (where you do and don't have additional content)? As a note, we are looking at switching things so that we inject Glimpse scripts without razor dependency (see #77).

**Comment by damienpontifex** [comment]
From my testing (adding local glimpse into src of my global.json file and testing on my project), Glimpse is still injected into PostContent for both cases: when it is the only one there and also when I'm injecting further additional content.

#77 looks like it might be a little way off, so I'd love to see this integrated into the current implementation so it doesn't effect users currently utilising the Razor/TagHelper approach.

**Comment by nikmd23** [comment]
This looks like a no brainer to me. Thanks for finding and fixing the bug @damienpontifex!

**Comment by avanderhoorn** [comment]
Thanks!

**Pull request merged**
