### PR TITLE
Add infrastructure, and sample functional test

### PR DESCRIPTION
**Pull request by rynowak**

### CODE REVIEW

**Comment by rynowak** [comment]
@avanderhoorn ping!

**Comment by avanderhoorn** [comment]
@rynowak sorry about not pulling it in yet... as you can see there are conflicts that are stopping it going in , mainly with the *.sln. I was going to ask you to fix them up, but I've been committing several changes over the last few days that have kept  changing the *.sln. So I didn't want to have to keep asking you to update each time if I missed pulling it in before a new change happened. I've got one more commit that is going in within the next hour and then if you can update, I'll bring it in.

**Comment by rynowak** [comment]
You can update this and pull it in on your side btw, it's fairly easy

```
git checkout -b rynowak-functional-test dev
git pull --rebase https://github.com/rynowak/Glimpse.Prototype.git functional-test
git rebase dev
```

**Comment by avanderhoorn** [comment]
This got pulled in manually, hence closing it off rather than pulling in via PR.

**Comment by avanderhoorn** [comment]
Thanks @rynowak!!!

**Pull request closed without merging**
