### PR TITLE
Networking for agent, server and client

### PR DESCRIPTION
**Pull request by avanderhoorn**
Eventually, it'd be great to "just use @signalr" everywhere. It uses web sockets, our preferred transport mechanism, when possible and falls back elegantly otherwise. Unfortunately, it looks like the next version of SignalR, presumably the one that supports CoreCLR, [is a year way from being released](https://github.com/aspnet/Home/wiki/Roadmap#future-work).

This issue captures the work required to work around the lack of SignalR.
## Between Agent & Server:

**In Process**
- [x] Leverage the in-process channel

** Distributed w/ both on Windows**
- [x] HttpClient posting with `Connection: Keep-Alive` in Glimpse Agent :lock:
- [x] Receiving endpoint in Glimpse Server :lock:
- [ ] ~~Private version of SignalR 2.x Server embedded into Glimpse Server :lock:~~
- [ ] ~~Private version of SignalR 2.x .NET Client embedded into Glimpse Agent :lock:~~

_No socket support for awhile, see [comment below](https://github.com/Glimpse/Glimpse.Prototype/issues/22#issuecomment-131638017)_

** Distributed w/ both on Linux**
- [x] HttpClient posting with `Connection: Keep-Alive` in Glimpse Agent :lock:
- [x] Receiving endpoint in Glimpse Server :lock:

** Distributed w/ mixed environment**
- [x] HttpClient posting with `Connection: Keep-Alive` in Glimpse Agent :lock:
- [x] Receiving endpoint/resource in Glimpse Server :lock:
## Between Server & Client:

**In Process**
- [x] Not applicable, client is always a separate process.

** Distributed w/ server on Windows**
- [ ] Server Sent Events Resource ([sample implementation](http://blogs.microsoft.co.il/gilf/2012/04/10/using-html5-server-sent-events-with-json-and-aspnet-mvc/)) :lock:
- [ ] [EventSource](http://caniuse.com/#feat=eventsource) Polyfill for non-supporting browsers.
- [ ] ~~Private version of SignalR 2.x Server embedded into Glimpse Server :lock:~~
- [ ] ~~Private version of SignalR 2.x JavaScript Client embedded into Glimpse Client :lock:~~

_No socket support for awhile, see [comment below](https://github.com/Glimpse/Glimpse.Prototype/issues/22#issuecomment-131638017)_

** Distributed w/ server on Linux**
- [ ] Server Sent Events Resource ([sample implementation](http://blogs.microsoft.co.il/gilf/2012/04/10/using-html5-server-sent-events-with-json-and-aspnet-mvc/)) :lock:
- [ ] [EventSource](http://caniuse.com/#feat=eventsource) Polyfill for non-supporting browsers.

Each item with a lock (:lock:) may require authentication. Let's not worry about that for this milestone, but be careful not to paint ourselves into a corner either.

### CODE REVIEW

**Comment by nikmd23** [comment]
I've updated the issue to capture these changes.

**Comment by avanderhoorn** [comment]
For data communications from the Glimpse Server to the Glimpse Client we could try using [Server Sent Events/EventSource](http://www.w3.org/TR/eventsource/) (and a pollyfill for IE). Looks like we should be able to do something quite simply for the Glimpse Client to Glimpse Server communication - [example](http://blogs.microsoft.co.il/gilf/2012/04/10/using-html5-server-sent-events-with-json-and-aspnet-mvc/)

**Comment by nikmd23** [comment]
Great. I've updated the issue to cover SSE as the main Server/Client connection strategy.

**Comment by avanderhoorn** [comment]
By default, with HTTP/1.1 the underlying socket should stay alive and HttpClient supports this. Currently about to start looking at SSE.

**Comment by avanderhoorn** [comment]
Brought this in for the moment... this will allow me to make the other chances that are needed in middleware first and then loop back to getting this up and running.

**Pull request merged**
