### PR TITLE
Resource module

### PR DESCRIPTION
**Pull request by avanderhoorn**
We need to add back in the concept of resources that can serve assets and data.

In the past, Glimpse resources could:
- Specify their parameters
- Write to the response stream
- Set headers
- Leverage decorators to perform common tasks

Do we want to keep the same requirements for 2.0?

### CODE REVIEW

**Comment by avanderhoorn** [comment]
Note, URI templates still need to be worked into the picture, but need to wait for further work to be done @darrelmiller. Will integrate as a separate PR when URI templates are ready.

**Comment by darrelmiller** [comment]
I was able to run existing the PCL DLL under CoreCLR (profile 259 is compatible) and I am in the process of fixing the Nuget right now.  Regarding parameter matching, I should have simple string parameters for path and query string working by Monday.

**Comment by avanderhoorn** [comment]
Sounds great mate! As you can see from the `GenerateUriTemplate` method above, the default case we are providing for users is fairly simple. That said, it is only used by the higher level API and users can still define their own templates for the lower level one. So having support for the higher level one is enough for now and as you get more coverage for the other cases, we can allow the lower level one to work with more complex cases. Thanks again!

**Comment by darrelmiller** [comment]
I just created a prerelease Nuget of UriTemplates that has a GetParameters(Uri) method that covers the basic scenarios that I believe you need.  http://www.nuget.org/packages/Tavis.UriTemplates/0.6.5-beta

**Comment by avanderhoorn** [comment]
I'll look at brining these in tonight. Will update with how I get on.

**Pull request merged**
